### ISSUE TITLE
using williamyeh/ansible:centos7, Enable the Docker daemon in systemd failing

### ISSUE THREAD

**Issue by desireBanse** [William-Yeh/docker-ansible#54]
Using
```
- name: Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no 
```
results in.
Job #45811 failed for 028da0c0:
"systemctl", "status", "docker"], "delta": "0:00:00.351030", "end": "2019-07-11 18:13:46.479587", "msg": "non-zero return code", "rc": 1, "start": "2019-07-11 18:13:46.128557", "stderr": "Failed to get D-Bus connection: Operation not permitted", "stderr_lines": ["Failed to get D-Bus connection: Operation not permitted"]
